kind: pipeline
name: default
steps:
- name: build_war
  image: maven:alpine
  commands:
  - mvn --batch-mode clean install
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token 
- name: build_and_publish
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dodev123/drone
    tags: latest
- name: deploy_to_kubernetes
  image: anoop600/updatedkubectl:3
  commands:
  - kubectl get nodes
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: pipelines
    
